### ISSUE TITLE
Not worrking (new update)

### ISSUE THREAD

**Issue by osinterface** [SpotX-Official/SpotX#25] opened 2022-03-03 11:53 UTC
## ℹ Computer information

- Spotify version:  Spotify für Windows 1.1.80.699.gc3dac750
- Windows version: 21H1 19043.1526
- PowerShell version: 5.1.19041.1320

## 📝 Description of the problem

1. i started spotify
2. it updated
3. Spotx was gone
4. I tried to reinstall
5. Error (see at Screenshots)

## 📷 Screenshots

<details>
<summary><small>Screenshot</small></summary><p>

![image](https://user-images.githubusercontent.com/100844613/156559519-7294586c-ab91-4d87-9f9d-a53ea836ea75.png)

</small></summary><p>

</details>

**Comment by amd64fox** [comment] 2022-03-03 15:12
Have you tried completely uninstalling spotify and re-running install.bat ?

**Comment by amd64fox** [comment] 2022-03-03 17:28
Upd.

From the reviews in telegram, it seems that there really are problems with the new version.

At the moment I have no way to fix it, no PC at hand, I will be at home within a week.

In the meantime, you can install the previous version from here https://cutt.ly/8EH6NuH

and choose to block updates when reinstalling the patch

**Comment by yodaluca23** [comment] 2022-03-10 01:28
Any ETA of when it will be fixed?

**Comment by amd64fox** [comment] 2022-03-10 12:32
I understand this is a duplicate of this [issue](https://github.com/amd64fox/SpotX/issues/26)

**Closed as completed by amd64fox** 2022-03-10 12:32 UTC
Labels: ❌ bug
